### ISSUE TITLE
Standard Winfile-AddOn

### ISSUE THREAD

**Issue by BaldwinTechnology** [Microsoft/winfile#110]
Hi Craig,

you asked me about a simpler version of the Winfile-AddOn.
What do you mean exactly? 

Only the empty switch-case?
Without comments?

Greetings Daniel

**Comment by BaldwinTechnology** [comment]
I posted an example.
https://github.com/Microsoft/winfile/issues/87

Craig said it should be simplified.
If you can have a look over it …

**Comment by craigwi** [comment]
Here are my thoughts:

1. wfext.h should be copied verbatim from master
2. languages in DLL.rc should include English in addition to German
3. compile with VS2015 or VS1027
4. for master, match target platform version of winfile itself 
5. use windows.h instead of afx*.h.
6. in dllmain.cpp, there are lots of IDM_* cases that do not appear to have a way to get executed.  If there are common scenarios, it would be great to have them work end to end.

Thanks!

**Comment by BaldwinTechnology** [comment]
Ok. I work on a improved version.

**Comment by BaldwinTechnology** [comment]
So Here's the new version.
If it is ok, then we can use it as template.

[WinFile-AddOn.zip](https://github.com/Microsoft/winfile/files/1950167/WinFile-AddOn.zip)

PS: It would be nice to have some sort of officially supported repository.
If I create it could be abandoned in the future.

**Comment by craigwi** [comment]
Thanks, I'll review.  I agree on a supported repo and was thinking of adding it here (e.g., under Samples\AddOn).

**Comment by DBJDBJ** [comment]
Great idea. But, where is the master plan it fits into? You know the drill:

1. vision
2. roadmap
3. cycling (develop, test, release, think what next)

Respectfully ...

**Comment by craigwi** [comment]
I fixed a few problems with menus to support extensions properly when the security menu is missing.

I also added a slightly cleaned up version of the addon from @BaldwinTechnology under samples/addon.
