### ISSUE TITLE
Stale messages in the interface

### ISSUE THREAD

**Issue by thecatkitty** [Microsoft/winfile#134]
During the preparation of Polish translation, I've faced a minor issue. Some of the messages tend to be unclear or inconsistent in the context of the current Windows UI. Namely:

- _iconizing_ instead of _minimizing_ (since Windows 95 we do not iconize anymore)
- arranging _icons_ (How do we call short title bars of the minimized windows in MDI then?)
- _directories_ instead of _folders_ (As the time passed, _directory_ started to mean, at least in the Windows world, a service or index, like _Directory Services_)

In translation and/or creating new functionality, should we use naming scheme from the source, or we should rewrite some of the messages using the current naming conventions? Eg. _Displays the contents of the current directory_ should be translated by me as _Wyświetla zawartość bieżącego katalogu_ or _Wyświetla zawartość bieżącego folderu_?

**Comment by ZanderBrown** [comment]
Personally I prefer the old style of icons (when referring to MDI children) but as Windows no longer supports them (to the best of my knowledge) it might be worth changing
![screenshot from 2018-04-26 20-41-45](https://user-images.githubusercontent.com/17074021/39328139-49c37468-4992-11e8-9184-b8678e137abf.png)
As to what you call the 'iconised' state in modern Windows I have no idea

**Comment by thecatkitty** [comment]
@NazmusLabs, I honestly think too, that moving away from the MDI in master branch would be a good idea. _File Manager_ is really a powerful and convenient tool, but playing with child windows is really annoying.

BTW, because of the limitations of my language I have to choose between "Menedżer plików systemu Windows" (_File manager **of** Windows_) or "Menedżer plików dla systemu Windows" (_File manager **for** Windows_). What would be a better translation?

**Comment by NazmusLabs** [comment]
Does anyone know how much work is needed to remove the MDI? Is it a simple set of code that tells Windows to not use MDI or would it need a rearchitecting of the file browser portion of the UI to "glue" it to the main window?

**Comment by malxau** [comment]
Removing MDI is kind of like pulling on a loose thread in a sweater.  You'll find yourself pulling for a long time, and at the end of it, might not be happy.

Consider the first step: remove all of the file/directory browsing windows from being owned by the master window.  At this point, there's some giant master window with a menu and a toolbar, and a couple of windows with files in them, but you need the master window to invoke any actions and when you do, the master window overlaps all of the child windows and obscures them.

So you go to the second step, and make the master window some kind of small/fixed size thing.  And then you have gimp.

So you realize that the menus and toolbars really need to be on the (plural) child windows.  But now you have a problem: there's a single UI thread driving all those windows, and the moment a user tries to invoke a dialog box that thread calls the synchronous DialogBox() function which stops work on all the other windows until it returns.  So you have all these visually decoupled windows that end up being tightly coupled.

After that, you have a couple options.  One would be giving each child window its own thread.  But then you realize that for many drag and drop operations you're going to be crossing the threads.  You can persevere with this and make it work, given enough effort.  Obviously you can forget about Windows 3.1 though, since the app is now thoroughly multithreaded.

The other option is you get rid of all classic dialog boxes and make them, as far as the system is concerned, modeless.  So when the user has two file browsing windows and invokes a dialog, the system just sees three disconnected windows whose messages are pumped by one thread.  This means you need to think about how the dialog communicates information back to its parent about when it's done and what to do etc, because this can't just be done by calling a function and having it return.  But then you have another problem, because sometimes you want modal behavior with respect to a dialog and a window, and since the system sees these objects as independent you get to go track the relationships and define the experience when the user attempts to interact with a window which is conceptually not the topmost window.  You have to catch the message, determine what happened, maybe change the active window to be something else, bring it to the top, flash it, etc.

****

One of the other strange things about this project is there's a lot of activity, but not a very shared vision, of where the app is trying to go.  A non-MDI File Manager doesn't seem very much like File Manager.  What I just described above seems much closer to Explorer without a Taskbar.  And you probably already have Explorer installed, and were avoiding it for some reason...

**Comment by ad43** [comment]
I'm not a Windows programmer, but I am a long-term user of Winfile since it's birth, lately on XP, 2003, 2008, Vista, Win8 and Win10, all of which have worked OK. The sole reason is that it has an MDI interface which allows two windows (each with folder list and folder file content) side-by-side. This format can be saved, together with 'home' drives and folders in each window.

This is what makes winfile different from Explorer (which, of course, I also use). It is the core reason it has survived for me. (1) When opened, it provides a stable point of reference (of my choice) in a complex filing system, which Explorer does not, and (2) it allows files and folders to be dragged from a Source (on the left) to a Destination (on the right). This is a logical and clear process.

Other actions are handled well with Explorer. Winfile is the equivalent of walking through the shelf racks of a book library. Explorer is nearer to asking the Librarian at a desk to find something for you.

I hope that these attributes survive the enthusiasm here for sweeping it into the 21st century. Good work...

Chris

**Comment by RMoDOOM** [comment]
I think MDI is incredibly useful in situations where you need a bunch of windows open pretty much constantly. File Explorer or tabbed file managers don't come close to the ease of use of an MDI file manager. I love MDI because it keeps clutter to a single window instead of 15 windows spread across 2 monitors. Sure, tabs would work, but that would limit drag and drop. "Add another column of tabs" would turn it from WinFile to Midnight Commander.

Aiming to remove a characteristic feature of WinFile because "it's outdated and Microsoft deprecated the design" is foolish.

**Comment by thecatkitty** [comment]
Okay, You've convinced me. Perhaps my annoyance was caused by using MDI in a nonstandard multiple display layout, which makes it impossible to have _full screen_ parent window.

Moreover, as @malxau claimed, moving away from MDI to SDI would become a lot of work with no use.

But with MDI there is still one thing I miss: Is there any possibility to have child windows resize, relative to the parent? Just like in IDE-interfaces having window docking areas.

Thus, I'm no longer supporting the idea of dropping MDI.

**Comment by craigwi** [comment]
I don't see any next steps here.  Reopen if you seen otherwise.
