### ISSUE TITLE
Sound engineering principles are telling me to fix everything that is "wrong" inside this code first.

### ISSUE THREAD

**Issue by DBJDBJ** [Microsoft/winfile#139]
One can either develop on Ad-Hoc basis. i.e. "debug" as bugs come along, or one can make the code more resilient and then debug the many bugs that will appear. Just like lifting the proverbial rock :)

I am here to help not to criticize. Unless help is not wanted.

One (probably unrelated to this bug) example: this code has no local static functions.  Thus "everything" is in essence global. Which works until it does not. I might fix this on the "my side" but will it be accepted? 

Sound engineering principles are telling me to fix everything that is "wrong" inside this code first. And then hunt for the bugs. Starting with  application design. In (small) manageable steps.

**Comment by malxau** [comment]
Unfortunately what's "wrong" with the code is a little subjective.

Taking the example here, you appear to acknowledge that using globals instead of statics hasn't really been a source of bugs.  (One could imagine bugs preventable with statics if globals were generating namespace collisions, but that seems unlikely with such a small amount of code.)  At the same time, it seems understood that making the changes here run a decent chance of introducing bugs.

The other thing I'd point out, and this goes back to my earlier post about not really sharing a vision, is that a lot of language changes are incompatible with running on older systems, so some of these changes would end up driving a hard fork in the code.  Whether it's a big deal depends on the value each individual places on downlevel support.

The bug in the other thread seemed to me to result from some bad design choices in Win32.  Unfortunately winfile is stuck with some of those choices by virtue of being Win32.  About the best it can do is abstract away the Win32-ness (eg. have wrapper functions that return the error without depending on a subsequent call to GetLastError.)

The big bugs I'm seeing stem from being an old codebase that was trying to be maximally compact by overloading bits which made sense when it was written but today just seems like the wrong tradeoff.  Those are tedious to change, but they don't require any language/compiler/library support to fix.

**Comment by NazmusLabs** [comment]
From my own experience over the years, I have gone through my personal phases of reorganizing my own systems and refactoring my code because of theoretical benefit. When I would get started, I'd be at a high point, excited about improving the back end structure. But as work piled up one over other, especially when having to fix more and more unforeseen effects of a particular change, I would always end up feeling a bit of regret taking on a massive task, pursuing some perceived efficiency that really didn't seem to make much practical difference on the end product.

So I had eventually changed my personal strategy. No, I didn't just give up improving things in the back end or refactoring code or restructuring my work flow. But rather than creating a massive project or task to "fix" things, I now try to take on a particular or improving things as their need arrives. When I see something that can directly benefit from refactoring, I thake the opportunity to do that, which improves a bit of the back end while having an impact on the end result as well.

The end result is that over a long period of time, I notice that a lot of things have been fixed through small, incremental, changes that didn't feel that daunting.

My belief is that changes in Winfile should take this approach. An application that is "mature", i.e. done, can benefit in following this model. So far, we are looking at a particular need, isolating it, making it bite-size, and addressing that need. Some changes improve on a previous commit. And we have already "modernized" portions of the code (such as adding a manifest file) as their need arrived.

I'm confident that over the long term, much of the code will be fixed, as more and more changes are made.

As for keeping the look and feel of the "classic" Winfile, that is, indeed, the vision, for a lack of a better word, for now. However, I must remind us all that an application can be modern while keep the "classic" feel. Take a look at Visual Studio IDE. It still has the classic feel of VS and VB6 IDE; yet it incorporates almost all modern UI guidelines, including tearing tabs, dark mise, dynamic workspace, etc.

What will be the state of Winfile in a few years remains a mystery, and that's what I love about software development. We see our work shaping a product over the years that we ourselves wouldn't have imagined.

Best

**Comment by DBJDBJ** [comment]
I do understand the wider context of this project, still @malxau nailed it: "not really sharing a vision".  

In the mean time, I shall "plough" on my side ...  with what I think are no brainers.  Like using _ASSERTE and a such ...  Just a common sense, nothing pompous.

Seeing the code from primordial soup of WIN development is fascinating. Thank you @craigwi .

**Comment by NazmusLabs** [comment]
Yup, the individual "no-brainer" changes can be short PRs, in keeping the way it's been done so far and seems to work pretty well.

**Comment by DBJDBJ** [comment]
@NazmusLabs  well can I then submit a PR , fixing these 147 "no brainers" VS2017 Code Analyzer is reporting?  One might think to fix these first and then go bug hunting? Here is the list for everyones perusal ...

[vs2017 code analyzer tool rezult.txt](https://github.com/Microsoft/winfile/files/1958879/vs2017.code.analyzer.tool.rezult.txt)

**Comment by NazmusLabs** [comment]
Yeah, I'd just submit a PR report with these fixes. It allows us to download and test the app for compat issues.

**Comment by DBJDBJ** [comment]
@craigwi  I submitted the PR to solve the Warning C6400. Just a solution not the use of it which requires a knowledge of the WINFILE internals which I do not have.

**Comment by craigwi** [comment]
@DBJDBJ, because your solution is not complete ("Just a solution not the use of it"), I will not accept it as is.  Furthermore, it includes files not related to the purpose of the commit.  In case you haven't read #88, please do.  Changing WinFile is hard and it takes time to understand things (the "internals" as you call it).

**Comment by DBJDBJ** [comment]
@craigwi  Agreed. I am sure you can see this is all about PR #88, mainly point 2.  I shall close the PR #156 and redo it properly. As for using it I shall do that too.  The key to the solution is to (have and) use the string ordinal comparisons when appropriate and  UI strings comparison when locale is involved.
