### ISSUE TITLE
Add Visual Styles support

### ISSUE THREAD

**Issue by daniel-white** [Microsoft/winfile#18]
Following one of the following strategies:

https://msdn.microsoft.com/en-us/library/windows/desktop/bb773175(v=vs.85).aspx

**Comment by daniel-white** [comment]
it makes things look better

![image](https://user-images.githubusercontent.com/735269/38528306-0494cd6e-3c2d-11e8-92ee-8705637eb00e.png)
![image](https://user-images.githubusercontent.com/735269/38528311-0bba1234-3c2d-11e8-81ee-2fad16ec7298.png)
![image](https://user-images.githubusercontent.com/735269/38528319-111f8330-3c2d-11e8-954e-2a45ff6383c2.png)

**Comment by NazmusLabs** [comment]
This is the first thing that came to my mind. Windows 10's visual style is much closer to the classic visual style but is less cluttered due to the unnecessarily onlines being removed.

Adding visual style support will keep the authentic feel in Windows 10 while keeping the app looking cleaner and easier on the eyes. The eye is distracted from unnecessary things, and a cleaner and focused UI allows the brain to focus better.

We as have learned a great deal about good UI design over the last decades, and we now undesirable the true value of a clean UI.

**Comment by craigwi** [comment]
What are the nature and extent of such changes?  Can they be turned on and off?

**Comment by NazmusLabs** [comment]
According to the MSDN documentation, all we need to do is call the common controls version 6 dll rather than version 5 through an app manifest. Their sample only shows C++. Do you think this would work in C?

Here's the MSDN article: https://msdn.microsoft.com/en-us/library/windows/desktop/bb773175(v=vs.85).aspx#using_manifests

**Comment by daniel-white** [comment]
@NazmusLabs yes it works - see my screenshots above.

**Comment by craigwi** [comment]
The #pragma works fine.  I just copied the exact text from the article and recompiled.  

However, I do wonder about the section "Making Your Application Compatible with Earlier Versions of Windows".    I'm ok with this change as long as it runs on all of the older Windows without hassle. 

Can someone check?

**Comment by daniel-white** [comment]
@craigwi how far back?

**Comment by craigwi** [comment]
Win7 for sure; XP as a bonus!

**Comment by ZanderBrown** [comment]
Visual Styles was introduced in XP so it'll work

**Comment by NazmusLabs** [comment]
@craigwi just took a read of that section. There are two parts. One is for versions of Windows prior to visual styles. That would be Windows 2000 or earlier. And the other part is to test the apps on High Contrast mode both in Windows 7 and in Windows 8 or 10. Windows 8 introduces a new high contrast infrastructure. So we would need to test it on the new and the old system. Testing high contrast on Windows 10 covers 8 and 8.1. Testing on Windiws 7 covers XP and Vista as well.

We definitely do need to test the high contrast settings to ensure the application doesn't break. But I am not sure if we need to test Windows 2000 or NT4... I mean I don't have any VMs in hand for those early NT version. I only have a 9x and 3x VM, and WinFile doesn't work on 9x or 3x, as verified by someone in another thread.

**Comment by craigwi** [comment]
For Windows Server, I think we should target the first version with Visual Styles.  Would that be Server 2003 or 2003 R2?

**Comment by NazmusLabs** [comment]
@craigwi Windows Server 2003 (R1) had visual styles, yes, as it was branched of the Windows XP RC codebase which had visual styles support. So the original server would work as well.

**Comment by craigwi** [comment]
@Azarien opened PR #92.  I am fine with enabling Visual Styles and have verified, at least on Windows 10, that high contrast mode works.

@daniel-white, @NazmusLabs, who should get the credit for the fix?

**Comment by NazmusLabs** [comment]
@craigwi I'd credit @daniel-white since they were the first to discover the relevant MSDN docs and to have the feature implemented. Of course, you also Implemented and verified it working, including in high contrast, which is important.

If anyone has an active machine running Windows 7 or older, it's crucial to text the app on high contrast as well as in the windows classic theme.

Otherwise, I have an archived Server 2008R2 VM that I can fire up, if need be.

**Comment by ZanderBrown** [comment]
I have access to 7 if someone can provide an exe of that branch

**Comment by daniel-white** [comment]
@craigwi  I'd give credit to @azarien. he did the actual work to get a PR in.

**Comment by craigwi** [comment]
I merged @Azarien's change PR #92.
