### ISSUE TITLE
File / Search...

### ISSUE THREAD

**Issue by weisborg** [Microsoft/winfile#190]
Checkbox for Subdirs in Results overlaps Help Button.

In early File Managers that were Pre-WinXP I seem to remember a lot more options like size ranges, file types, dates, etc.  Should have even been text within the file since that is the biggest thing that drove me nuts enough to make my own search utility when XP came out.

I'm guessing the Since field is for dates, but even in early File Managers there was some type of Pickers or masks or something.  It seems too unclear as to the format of data for that field.

**Comment by ZanderBrown** [comment]
> early File Managers

without looking outside Windows you'd be struggling to find anything earlier unless you count MS-DOS Executive

Perhaps I'm missremembering but I'm pretty sure XP supported searching by filesize & contents in the search companion

**Comment by weisborg** [comment]
I guess I was thinking of Win95 like [Here](http://hallofshame.gp.co.at/find95.htm)

This looks more like the Win 3.x...although images of it don't even show a Since field.  I'll have to look on my Windows 3.11 when I get home.

I wish the Win9x would go Open Source.  WinXP Search was horrible.  It used some weird template system you had to define how to search different file types in the registry and DLLs to parse that type, etc.  I usually want to just do a binary search on a file for a string.

**Comment by craigwi** [comment]
I added the "Since" feature to the search dialog box some years ago.  See item 9 in https://github.com/Microsoft/winfile/blob/master/README.md.

As for the date format accepted, the API used to parse the date is: VarDateFromStr(szStart, lcid, 0, &date);  See wfdlgs2.c, line 160.

There have been suggestions / requests to allow other formats.  I don't remember the issue number.
