### ISSUE TITLE
OSX Support

### ISSUE THREAD

**Issue by dataf3l** [Microsoft/winfile#197]
We badly miss this...

**Comment by thecatkitty** [comment]
As for now, it seems that any form of OSX support is a no-go, as WinFile is 100% WinAPI.

**Comment by thecatkitty** [comment]
I'm trying to decode where You got an idea that a program written in C must be portable.

C is just a language. It has its standard library but WinFile (which used to be an inseparable part of the Microsoft Windows operating system) didn't use it because of being a GUI application, so it was written in WinAPI. The only way to use it on non-Windows operating systems is to use Wine or some another form of WinAPI compatibility layer.

**Comment by dataf3l** [comment]
I guess I can just fire virtualbox then...
That's probably easier

**Comment by craigwi** [comment]
yes, probably.
