### ISSUE TITLE
3.99TB Limit

### ISSUE THREAD

**Issue by dos2k10** [microsoft/winfile#257]
Hello,
Thank you for bringing this utility back. I immediately saw that this remastered utility cannot show drive usage or drive total size larger than 3.99TB. I assume this is some programming limitation. Here is a screenshot of my network drive alongside File Explorer.
![image](https://user-images.githubusercontent.com/68808178/88476050-6fb8a200-cef2-11ea-85c8-112e61aaf39f.png)

**Comment by Diablo-D3** [comment]
(2**32 - 1) / 1024 / 1024 / 1024 = 3.99TB

So, it seems File Manager also does not use SI bytes.

**Comment by malxau** [comment]
GetDiskFreeSpace has a limitation on 2^32-1 clusters, and this program doesn't appear to use GetDiskFreeSpaceEx, which exists to a) overcome this and b) be easier to use.  GetDiskFreeSpaceEx has existed since NT4/Win95 OSR2.

However, this implies that the file share has/is reporting a 1Kb cluster size, which is a strange configuration.  Is this expected?  Normal NTFS uses 4Kb by default, and is itself limited to 2^32-1 clusters, so the winfile limit and NTFS limit are the same.

**Comment by craigwi** [comment]
Looks pretty straight forward to switch to GetDiskFreeSpaceEx.

**Comment by craigwi** [comment]
@dos2k10 can you confirm that the PR https://github.com/microsoft/winfile/pull/285 by @malxau solves this problem?

**Comment by dos2k10** [comment]
@craigwi I believe it does solve this issue. I'm not a programmer nor used to building applications to test them. If there is a test build available, then I can run it against my scenario here with the 10.8TB Network Drive. Hoping to get WinFile to match with Explorer.

**Comment by craigwi** [comment]
I put a private build on https://winfilerelease.blob.core.windows.net/pr285test/Winfile.exe (x64 release).  Let me know if you can validate the fix.

**Comment by dos2k10** [comment]
Thank you! I was able to test this and confirm that it now shows more than 3.9TB.
![image](https://user-images.githubusercontent.com/68808178/151059466-fe26d996-8308-4359-a2b5-be3b2fad544c.png)
