### ISSUE TITLE
Allow a directory to be specified on the command line

### ISSUE THREAD

**Issue by 0penrc** [microsoft/winfile#266]
For example:
If i run Winfile C:\Windows\
Winfile will open C:\Windows\.
Also make it that if a CLSID is detected that it opens via Explorer, this can be useful for those who modify HKEY_CLASSES_ROOT\Folder in case someone wants to change their default file manager to Winfile.

**Comment by malxau-msft** [comment]
As you've probably noticed, WinFile currently treats any command line as a program to execute, and the default file association for a directory is Explorer, so specifying a directory to Winfile ends up opening Explorer.

I think what we should do is check if the argument refers to a directory, and if so, consume it as one.  If it's anything else, we can leave the current behavior - and a CLSID would count as "anything else."

That leaves some strange behavior if a non-existing directory is specified, because Winfile won't know it's a directory, and would end up triggering the regular flow to look for a file with a .exe extension, etc.
