### ISSUE TITLE
Provide different versions through git branches

### ISSUE THREAD

**Issue by pSchaub** [Microsoft/winfile#27]
I think it would be helpful to provide the different versions __through git branches__.

Idea for further development:
- a git branch named "master" with the latest stable source code
- a git branch named "develop" or "dev" or similar with the latest unstable source code

Idea about the old code (archives):
- a git branch named "original" with the code from November 2007
- a git branch named "original_plus" with the code from November 2007 + fixes

**Comment by craigwi** [comment]
Hi, I specifically did not create anything to demarcate the "original" original code since I was required to make some minor edits prior to release and because i didn't think it a useful starting point.  The readme.md contains the list of the changes (there were also some changes to comments such as consistent Copyright notices).

You can create your own branch for original_plus, but I didn't create one because it is never going to change.

As for the other branches, I'm open to evolving how this is done.  For now, there is just master.

Other thoughts?

**Comment by NazmusLabs** [comment]
Yeah, for now, I don't think we need a dev branch. I don't see a massive amount of new commits that contain a lot of breaking changes or big upgrades. Most PR as of now seem to be polishing and minor fixes, and the ones merged to master seemed to be fine with no bugs.
