### ISSUE TITLE
Slowness/Problems with Network Drives

### ISSUE THREAD

**Issue by dk2112** [microsoft/winfile#273]
When accessing a network drive on a remote server (i.e. server at a distant site or across internet/VPN), I am seeing slowness drilling down into subdirectories.  It seems that winfile is parsing the entire directory tree when you try to open a subdirectory.  Winfile basically freezes, with the exception of 'Directories Read' in the lower left hand corner, which slowly increments.  When it finishes counting, it un-freezes and works properly.  I've attached a PDF with details.  The original winfile does NOT duplicate this behavior (I tried it via the wfrevive hack).  I've also had trouble with winfile 'hanging' upon opening if you had a window open with a network drive that no longer exists.  You either have to re-map the drive or map another share to the same drive letter in order to get winfile to open.
[PrintSmart Scan.pdf](https://github.com/microsoft/winfile/files/6748980/PrintSmart.Scan.pdf)

**Comment by malxau** [comment]
Based on the 'Directories Read' comment, this is populating the tree.  It doesn't parse the tree recursively forever - it parses one extra level deep to check if each directory contains a directory in order to render the '+' in the folder icon.  Once it finds a directory within a child, it stops the search, so the worst case is directories with lots of files, where it will scan the whole thing.

The change between this code and the original is: https://github.com/microsoft/winfile/blob/73b0906a1f7d18914ed1d5caf928b26582661f1f/src/treectl.c#L789 

The original code would only do the second level recursion when "Indicate Expandable Branches" in the View menu is selected.  The new code does it always.  The comment appears correct though - horizontal arrows won't expand the tree unless this navigation is performed.  I don't (currently) know why this is.

**Comment by dk2112** [comment]
Thanks for looking into it.  The curious thing is that Windows Explorer 
does not experience slowness in the same situation.

------ Original Message ------
