### ISSUE TITLE
Is there a way to change the date format from : month day year to : day month year format ?

### ISSUE THREAD

**Issue by marcorocco2102** [microsoft/winfile#332]
Hi,
in winfile I get the date format of the file in the month/day/year

but I wonder if is there a way to change it on day/month/year format if is possible. Thanks

**Comment by malxau** [comment]
Winfile should follow the system configuration.  In Windows 10, see Settings, Time & Language, Region, and Regional Format.  After changing this, winfile needs to be restarted to observe the change.

**Comment by marcorocco2102** [comment]
Hi, in Windows 10 the Winfile shown in the desired format day/month/year. But strangely in Windows 11 looks like the format month/day/year cannot be changed to month/day/year.

If anyone have any ideas, thanks

**Comment by malxau** [comment]
Thanks for the additional information.  I wasn't able to reproduce this on Windows 11.  In the past when I've seen this type of behavior, it's because the system updates an x64 registry key describing the desired setting and a 32 bit process reads the 32 bit registry and doesn't observe the update.

Is there any more information you can provide about:

- How did you install WinFile (what was the source of the binary?)
- Is it an x64 binary (and an x64 Windows 11?)
- How did you update the system's configuration for date formatting? Was it via the Settings app or something else?

Thanks in advance.

**Comment by marcorocco2102** [comment]
Windows 11 64 bit, but maybe I think to be solve the problem: I have install the kb5013943 to update Windows 11 and seems ok. Thanks
