### ISSUE TITLE
winfile do not work on windows pe 10

### ISSUE THREAD

**Issue by snowdream** [microsoft/winfile#391]
It crashed on  windows pe 10:

VCRUNTIME140.dll Not Found、

I see: 
Runtime:
Winfile.exe depends on the VS 2015 C++ runtime; you can download that from
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by malxau** [comment]
It is expected that WinFile requires the Visual C++ runtime.  I don't think that link is the right one though - download the latest from https://aka.ms/vcredist .  After installing the runtime, does it still fail to launch?

**Comment by snowdream** [comment]
I try to install vcredist on Win 10 PE,But failed.

vcredist  can not be installed on Win 10 PE,

**Comment by clzls** [comment]
For your information, I had copied these files to the same folder of WinFile executable from my Win 10 installation, and WinFile seemed to be working normally in both Win 10 PE and Win 11 PE:
```
msvcp140.dll
vcruntime140.dll
vcruntime140_1.dll
```

(I know it may be discouraged, but sometimes having suitable tools running under PE is very comfortable.)

**Comment by malxau** [comment]
Oh, I fully understand why it'd be useful to have Winfile run on WinPE.  What I don't know is the best way to support it.  Normally Microsoft distributes software linked against the C runtime as a DLL, because doing so allows the DLL to be updated independently of the program.  WinPE either wants to be statically linked with the runtime DLL, or possibly using an older compiler, to ensure the DLL is already there.  Neither of these would be good to do except to support WinPE.

Good to know that it works by copying the DLLs though.
