### ISSUE TITLE
"Format disk..." doesn't work

### ISSUE THREAD

**Issue by daviunic** [Microsoft/winfile#62]
On Windows 10 x64, using the "Format disk..." option in the Disk menu results in an error message saying "File manager cannot obtain disk information. Make sure the disk is in the drive." .

I'm not sure what this is suppose to do (perhaps it was only meant to format floppies?), but it would be nice if it actually called the standard format disk dialog of Windows, like Explorer does.

**Comment by NazmusLabs** [comment]
I think we should have that menu item just call the native Windows format disk UI, the one you get when you right click a drive on file explorer and click "Format Disk...".

**Comment by T8z5h3** [comment]
ether that or call disk management MMC

**Comment by matthewjustice** [comment]
@daviunic - Are you referring to the menu item in the screenshot below? 

<img width="173" alt="format" src="https://user-images.githubusercontent.com/18629374/38650676-27b4cebc-3dcb-11e8-8dbb-c853e24f11b2.png">

Because if so, it is always disabled for me (and I would assume for most users today), because I have no floppy drives. See this line of code:

https://github.com/Microsoft/winfile/blob/a06f6f19a9eedbbd1fbcd6462737055be8c39eb9/src/wfinit.c#L411

I'm curious, is it enabled for you, and do you have a floppy drive on your system? Thanks!

**Comment by craigwi** [comment]
It is clear that the old FormatDisk code isn't doing what we think is should.  That's also true of other things like the old Security menu.  

I would prefer to map out a simple approach to enable this functionality (FormatDisk in this case) or, if that is not possible, to delete the feature.

**Comment by matthewjustice** [comment]
I like @NazmusLabs's suggestion of invoking the current Windows format disk UI (shown below). However, I also have a concern with this approach. 

Today when a user invokes this UI from the shell, explorer.exe calls ShFormatDrive which displays the UI. Unfortunately, [MSDN says that ShFormatDrive is **deprecated**](https://msdn.microsoft.com/en-us/library/windows/desktop/bb762169(v=vs.85).aspx). So if we want to use this exact UI, we'll need to rely on a deprecated function. Of course explorer.exe is still using it, so that's something. I haven't yet come across a supported Windows API function that does the same thing.

<img width="189" alt="format-explorer2" src="https://user-images.githubusercontent.com/18629374/38655414-7b97a786-3de2-11e8-9110-c4cba60a6268.png">

**Comment by daviunic** [comment]
@matthewjustice it is enabled for me and invoking it causes the error I mentioned. I have a USB card reader installed and for every type of card it supports it displays a drive in explorer, acting much like a floppy drive would. So it seems it misdetects removable drives which behave this way.

**Comment by T8z5h3** [comment]
@daviunic that would make sense because to windows your Card reader looks like a USB Floppy drive but i think how the programming interacts with the card reader is incomparable.

**Comment by NazmusLabs** [comment]
@matthewjustice I'm shocked to see this listed as deprecated. Usually things that get deprecated usually have had newer API calls or alternatives for a long time now. This doesn't seem to have any. Or does MS want to use the CMD for that now? And, like you said, Explorer uses this....

Regardless, I'm confident this feature won't go away anytime soon until Microsoft introduces an alternative and creates a redirect.

For example, the classic "calc" run command now redirects a call to launch the Calculator UWP app so that things like hardware calculator buttons on keyboards don't break.

**Comment by T8z5h3** [comment]
@NazmusLabs i feel that microsoft want the programer to do the simplest things when it comes to formatting witch is why they have a API call for the built in formatting tool

**Comment by NazmusLabs** [comment]
@T8z5h3 yes, but in this case, it is the API that you are referring to itself that has apparently been deprecated, which is the reason for my surprise.

**Comment by matthewjustice** [comment]
PR #108 submitted. I went with the SHFormatDrive approach.

**Comment by ZanderBrown** [comment]
Would make sense, it seems the item is enabled based on the value of nFloppies

https://github.com/Microsoft/winfile/blob/c57f75539c91c461754910850e3d8c7b01e65640/src/wfinit.c#L1332-L1347

And as you can see that value is calculated based on the assumption a removable drive is a floppy disk so as far as the logic cares your external harddrive is a floppy

**Comment by NazmusLabs** [comment]
@zanderbrown nice! Thanks for confirming my assumption. So it appears it may not have anything to do with having a card reader, but rather any removal drive. 🙂

**Comment by craigwi** [comment]
We have a solution and there don't appear to be specific next steps here.  Reopen if you disagree.
